// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationDefinition } from "./AutomationDefinition";
import type { AutomationScope } from "./AutomationScope";

export type AutomationUpsertParams = { threadId: string, scope: AutomationScope, automation: AutomationDefinition, };
