// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationLimits } from "./AutomationLimits";
import type { AutomationMessageSource } from "./AutomationMessageSource";
import type { AutomationPolicyCommand } from "./AutomationPolicyCommand";
import type { AutomationTrigger } from "./AutomationTrigger";

export type AutomationDefinition = { id: string | null, enabled: boolean, trigger: AutomationTrigger, messageSource: AutomationMessageSource, limits: AutomationLimits, policyCommand: AutomationPolicyCommand | null, };
