// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Automation } from "./Automation";
import type { AutomationUpdateType } from "./AutomationUpdateType";

export type AutomationUpdatedNotification = { threadId: string, runtimeId: string, updateType: AutomationUpdateType, automation: Automation | null, message: string | null, };
