// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationLimits } from "./AutomationLimits";
import type { AutomationMessageSource } from "./AutomationMessageSource";
import type { AutomationPolicyCommand } from "./AutomationPolicyCommand";
import type { AutomationScope } from "./AutomationScope";
import type { AutomationTrigger } from "./AutomationTrigger";

export type Automation = { runtimeId: string, id: string, scope: AutomationScope, enabled: boolean, paused: boolean, stopped: boolean, runCount: number, nextFireAt: bigint | null, lastError: string | null, trigger: AutomationTrigger, messageSource: AutomationMessageSource, limits: AutomationLimits, policyCommand: AutomationPolicyCommand | null, };
