// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotCycleKind } from "./PilotCycleKind";
import type { PilotStatus } from "./PilotStatus";

export type PilotRun = { goal: string, status: PilotStatus, startedAt: bigint, deadlineAt: bigint | null, updatedAt: bigint, iterationCount: number, pendingCycleKind: PilotCycleKind | null, activeCycleKind: PilotCycleKind | null, activeTurnId: string | null, lastSubmittedTurnId: string | null, wrapUpRequested: boolean, wrapUpRequestedAt: bigint | null, stopRequestedAt: bigint | null, lastError: string | null, statusMessage: string | null, lastProgressAt: bigint | null, lastCycleCompletedAt: bigint | null, lastCycleSummary: string | null, lastCycleKind: PilotCycleKind | null, lastAgentMessage: string | null, };
