// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotRun } from "./PilotRun";
import type { PilotUpdateType } from "./PilotUpdateType";

export type PilotUpdatedNotification = { threadId: string, updateType: PilotUpdateType, run: PilotRun | null, message: string | null, };
