// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { PermissionProfile } from "./PermissionProfile";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { Thread } from "./Thread";

export type ThreadReadResponse = { thread: Thread, approvalPolicy: AskForApproval | null, approvalsReviewer: ApprovalsReviewer | null, sandbox: SandboxPolicy | null, permissionProfile: PermissionProfile | null, };
