mod controller;
mod discovery;
mod journal;
mod memory;
mod parallel_workspace;
mod policy;
mod policy_config;
mod reporting;
mod research_workspace;
mod runtime;
mod stages;
pub mod tools;
mod validation;
mod workspace;

pub use controller::AutoresearchControllerSnapshot;
pub use controller::PortfolioRefreshStatus;
pub use controller::PortfolioRefreshStatusKind;
pub use controller::PortfolioRefreshTriggerKind;
pub use controller::load_autoresearch_controller_snapshot;
pub use discovery::AutoresearchDiscoveryReason;
pub use discovery::AutoresearchDiscoveryRequest;
pub use discovery::build_discovery_prompt;
pub use journal::AutoresearchApproachEntry;
pub use journal::AutoresearchApproachStatus;
pub use journal::AutoresearchApproachSummary;
pub use journal::AutoresearchConfigEntry;
pub use journal::AutoresearchControllerDecisionEntry;
pub use journal::AutoresearchDiscoveryEntry;
pub use journal::AutoresearchExperimentEntry;
pub use journal::AutoresearchExperimentStatus;
pub use journal::AutoresearchJournal;
pub use journal::AutoresearchJournalSummary;
pub use journal::AutoresearchPortfolioRefreshDecision;
pub use journal::AutoresearchSelectionDecision;
pub use journal::AutoresearchSynthesisSuggestion;
pub use journal::MetricDirection;
pub(crate) use parallel_workspace::AutoresearchParallelWorkspaceLease;
pub use parallel_workspace::AutoresearchParallelWorkspaceManager;
pub use policy_config::PortfolioRefreshPolicy;
pub use policy_config::PortfolioRefreshPolicySettings;
pub use policy_config::SelectionPolicy;
pub use policy_config::SelectionPolicySettings;
pub(crate) use reporting::refresh_playbook_artifact;
pub(crate) use reporting::write_wrap_up_report_artifact;
pub use research_workspace::AutoresearchResearchWorkspace;
pub use runtime::AutoresearchCycleKind;
pub use runtime::AutoresearchCyclePlan;
pub use runtime::AutoresearchMode;
pub use runtime::AutoresearchRunState;
pub use runtime::AutoresearchRuntime;
pub use runtime::AutoresearchStatus;
pub use runtime::PendingRunResult;
pub use runtime::build_init_prompt;
pub use runtime::build_open_init_prompt;
pub use runtime::clear_thread_state;
pub use stages::AutoresearchStageProgress;
pub use stages::AutoresearchStageTarget;
pub use stages::load_stage_progress;
pub use validation::AutoresearchValidationEntry;
pub use validation::AutoresearchValidationOutcome;
pub use validation::AutoresearchValidationType;
pub use validation::EvaluationGovernanceSettings;
pub use validation::ValidationPolicySettings;
pub(crate) use validation::enforce_locked_metrics;
pub use validation::load_evaluation_governance_settings;
pub use validation::load_validation_policy_settings;
pub use validation::render_governance_line;
pub(crate) use validation::render_policy_issue_lines;
pub use validation::render_validation_gate_line;
pub use validation::render_validation_policy_line;
pub(crate) use validation::render_validation_prompt_lines;
pub use validation::validation_gate_for_status;
pub use workspace::AutoresearchWorkspace;
pub use workspace::AutoresearchWorkspaceMode;
pub use workspace::PreparedAutoresearchWorkspace;

pub const AUTORESEARCH_JOURNAL_FILE: &str = "autoresearch.jsonl";
pub const AUTORESEARCH_DOC_FILE: &str = "autoresearch.md";
pub const AUTORESEARCH_SCRIPT_FILE: &str = "autoresearch.sh";
pub const AUTORESEARCH_CHECKS_FILE: &str = "autoresearch.checks.sh";
pub const AUTORESEARCH_IDEAS_FILE: &str = "autoresearch.ideas.md";
pub const AUTORESEARCH_PLAYBOOK_FILE: &str = "autoresearch.playbook.md";
pub const AUTORESEARCH_REPORT_FILE: &str = "autoresearch.report.md";
